config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :brands, only: [:new, :create] do
    collection do
      get 'explore'
      get 'saved'
      get 'local'
      # get 'new'
      post 'explore'
    end
  end

  get 'brands/naughty/:id', to: 'brands#naughty', as: 'naughty_brand'
  get 'brands/ecofriendly/:id', to: 'brands#ecofriendly', as: 'ecofriendly_brand'
  get 'my_impact', to: 'users#my_impact'
  post 'brands/:id/saved', to: 'brands#save', as: 'save'
  get 'brands/ecofriendly/:id/share', to: 'brands#share', as: 'share_brand'
end

app/models/user.rb
class User < ApplicationRecord
  # check address can be geocoded
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_many :saved_brands
  has_many :brands, through: :saved_brands
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :preference_price, presence: true, numericality: { only_integer: true }, inclusion: { in: 1..5 }
  validates :preference_style, presence: true, inclusion: { in: %w[modern outdoor minimalist retro boujie arty
                                                                   scandinavian grunge formal lounge boho] }
  # validates :address, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_impact
    if current_user.brands_shared.nil?
      @brands_shared = 0
    else
      @brands_shared = current_user.brands_shared
    end

    if current_user.brands_referred.nil?
      @brands_referred = 0
    else
      @brands_referred = current_user.brands_referred
    end

    if current_user.friends_referred.nil?
      @friends_referred = 0
    else
      @friends_referred = current_user.friends_referred
    end

    @total_points = @brands_shared.to_i + @brands_referred.to_i + @friends_referred.to_i
  end
end

app/views/users/_my_impact_cards.erb
<div class="layout">
  <div class="back-btn-container">
    <%= link_to 'javascript:history.go(-1);' do %>
      <button class="icon-btn">
        <i class="fas fa-chevron-left"></i>
      </button>
    <% end %>
  </div>
  <div class = "container">
    <h1 class="text-white">My Impact</h1>
    <div class="card-deck">

<%# FIRST CARD %>
      <div class="my-impact">
        <div class="card-body">
          <h5 class="card-title"></i> Brands shared</h5>
          <div class= "text">
          <% if @brands_shared.nil? %>
            <p class="card-text">Share brands to get our unique discount code!</p>
          <%else%>
            <p class = "card-text">Your unique discount code: </p>
            <p class = "discount-text">Style-in-peace-100</p>
          <%end%>
          </div>
          <div id="card-points">
            <% if @brands_shared.nil? %>
              <h5 class = "card-points">0</h5>
            <%else%>
              <h5 class = "card-points"><%=@brands_shared%></h5>
            <%end%>
          </div>
        </div>
        <div class="card-footer">
          <div class = "my-impact-btn">
            <button class="add" data-toggle="modal" data-target="#shareModal">
              <i class="fas fa-share"></i>               Share
            </button>
          </div>
        </div>
      </div>

<%# SECOND CARD %>
      <div class="my-impact">
        <div class="card-body">
          <h5 class="card-title"> Brands referred</h5>
          <div class= "text">
            <p class="card-text">Let us know of any sustainable brands to include!</p>
          </div>
          <div id="class-points">
            <% if @brands_referred.nil? %>
              <h5 class = "card-points">0</h5>
            <%else%>
              <h5 class = "card-points"><%=@brands_referred%></h5>
            <%end%>
          </div>
        </div>
        <div class="card-footer">
            <%= link_to brands_path do %>
            <div class = "my-impact-btn">
              <button class="add">
                <i class="fas fa-plus"></i>  Add a brand
              </button>
            </div>
          <% end %>
        </div>
      </div>

<%# THIRD CARD %>
      <div class="my-impact">
        <div class="card-body">
          <h5 class="card-title">Friends referred</h5>
            <div class= "text">
              <p class="card-text">Tell your friends about us!</p>
            </div>
            <div id="card points">
              <h5 class="card-points">0</h5>
            </div>
        </div>
        <div class="card-footer">
          <div class = "my-impact-btn">
            <button class="add" data-toggle="modal" data-target="#shareModal">
              <i class="fas fa-share"></i>               Refer a friend
            </button>
          </div>
        </div>
      </div>

<%# FOURTH CARD %>

      <div id="total-points" class="my-impact">
        <div class="card-body">
          <h5 class="card-title">Total points</h5>
          <% if current_user.brands_shared.nil?%>
            <p class="card-text"> No points yet :( </p>
          <%else%>
            <p class = "card-text">Thank you for your support!</p>
          <%end%>
          <div>
            <h5 id="card-total-points" class="card-points"><%=@total_points%></h5>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/my_impact.html.erb
<%= render 'shared/navbar_transparent' %>
<div class="impact">
  <%= render 'my_impact_cards' %>
</div>