config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :brands, only: [:new, :create] do
    collection do
      get 'explore'
      get 'saved'
      get 'local'
      # get 'new'
      post 'explore'
    end
  end

  get 'brands/naughty/:id', to: 'brands#naughty', as: 'naughty_brand'
  get 'brands/ecofriendly/:id', to: 'brands#ecofriendly', as: 'ecofriendly_brand'
  get 'my_impact', to: 'users#my_impact'
  post 'brands/:id/saved', to: 'brands#save', as: 'save'
  get 'brands/ecofriendly/:id/share', to: 'brands#share', as: 'share_brand'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer card">
  <div class="content">
    <div class="logo">
      <div class="navbar-brand">
        <i class="fas fa-globe-americas fa-2x"></i>
        <div class="style-in-peace">
          <div class="style"><%= "STYLE" %></div>
          <div class="peace"><%= "IN PEACE" %></div>
        </div>
      </div>
    </div>
    <div class="purpose">
      <%= "Carefully curated to help  save the world one outfit at a time"  %>
    </div>
    <div class="copyright">
      <%="©2021 by styleinpeace."%>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class= "navbar navbar-expand-lg navbar-light" id="white">
  <div class="logo">
    <%= link_to root_path, class: "navbar-brand" do %>
    <i class="fas fa-globe-americas fa-2x"></i>
    <div class="style-in-peace">
      <div class="style"><%= "STYLE" %></div>
      <div class="peace"><%= "IN PEACE" %></div>
    </div>
    <% end %>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item nav-link">
        <%= link_to root_path do %>
             <i class="fas fa-home"></i>
             Home
        <% end %>
      </li>
        <li class="nav-item nav-link">
        <%= link_to explore_brands_path do %>
             <i class="fas fa-compass"></i>
             Explore
        <% end %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item nav-link">
          <%= link_to local_brands_path do %>
               <i class="fas fa-map-marker-alt"></i>
               Local
          <% end %>
        </li>
        <li class="nav-item nav-link">
          <%= link_to saved_brands_path do %>
               <i class="fas fa-heart"></i>
               Saved
          <% end %>
        </li>
         <li class="nav-item nav-link">
          <%= link_to my_impact_path do %>
               <i class="fas fa-globe-americas"></i>
               My impact
          <% end %>
        </li>
        <% end %>
    </ul>
      <div class="nav-item nav-link black">
        <div class="btn-group">
          <button type="button" class="btn btn-secondary dropdown-toggle transparent-btn black" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user-circle black"></i>
          </button>
          <div class="dropdown-menu dropdown-menu-right">
            <% if user_signed_in? %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", method: :delete %>
            <% else %>
              <%= link_to "Login", new_user_session_path, class: "dropdown-item" %>
            <% end %>
            <button class="dropdown-item" type="button">Account</button>
            <button class="dropdown-item" type="button">Help</button>
          </div>
        </div>
      </div>
  </div>
</nav>

app/views/shared/_navbar_transparent.html.erb
<nav class= "navbar navbar-expand-lg navbar-light transparent">
  <div class="logo">
    <%= link_to root_path, class: "navbar-brand white" do %>
    <i class="fas fa-globe-americas fa-2x white"></i>
    <div class="style-in-peace">
      <div class="style"><%= "STYLE" %></div>
      <div class="peace"><%= "IN PEACE" %></div>
    </div>
    <% end %>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item nav-link">
        <%= link_to root_path, class:"white" do %>
             <i class="fas fa-home white"></i>
             Home
        <% end %>
      </li>
        <li class="nav-item nav-link">
        <%= link_to explore_brands_path, class:"white" do %>
             <i class="fas fa-compass white"></i>
             Explore
        <% end %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item nav-link">
          <%= link_to local_brands_path, class:"white" do %>
               <i class="fas fa-map-marker-alt white"></i>
               Local
          <% end %>
        </li>
        <li class="nav-item nav-link">
          <%= link_to saved_brands_path, class:"white" do %>
               <i class="fas fa-heart white"></i>
               Saved
          <% end %>
        </li>
        <li class="nav-item nav-link">
          <%= link_to my_impact_path, class:"white" do %>
               <i class="fas fa-globe-americas white"></i>
               My impact
          <% end %>
        </li>
      <% end %>
    </ul>
    <div class="nav-item nav-link">
      <div class="btn-group">
        <button type="button" class="btn btn-secondary dropdown-toggle transparent-btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user-circle white"></i>
        </button>
        <div class="dropdown-menu dropdown-menu-right">
          <% if user_signed_in? %>
            <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", method: :delete %>
          <% else %>
            <%= link_to "Login", new_user_session_path, class: "dropdown-item" %>
          <% end %>
          <button class="dropdown-item" type="button">Account</button>
          <button class="dropdown-item" type="button">Help</button>
        </div>
      </div>
    </div>
  </div>
</nav>