config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :brands, only: [:new, :create] do
    collection do
      get 'explore'
      get 'saved'
      get 'local'
      # get 'new'
      post 'explore'
    end
  end

  get 'brands/naughty/:id', to: 'brands#naughty', as: 'naughty_brand'
  get 'brands/ecofriendly/:id', to: 'brands#ecofriendly', as: 'ecofriendly_brand'
  get 'my_impact', to: 'users#my_impact'
  post 'brands/:id/saved', to: 'brands#save', as: 'save'
  get 'brands/ecofriendly/:id/share', to: 'brands#share', as: 'share_brand'
end

app/models/brand.rb
class Brand < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_many :saved_brands
  has_many :users, through: :saved_brands
  has_many_attached :photos


  validates :name, presence: true, uniqueness: true
  validates :website_url, presence: true
  validates :price_category, numericality: { only_integer: true }, inclusion: { in: 1..3 }, allow_blank: true
  validates :rating_earth, numericality: { only_integer: true }, inclusion: { in: 1..5 }, allow_blank: true
  validates :rating_people, numericality: { only_integer: true }, inclusion: { in: 1..5 }, allow_blank: true
  validates :rating_animals, numericality: { only_integer: true }, inclusion: { in: 1..5 }, allow_blank: true
  validates :rating_materials, numericality: { only_integer: true }, inclusion: { in: 1..5 }, allow_blank: true
  validates :style, presence: true, inclusion: { in: %w[modern outdoor minimalist retro boujie arty scandinavian grunge
                                                        formal lounge boho] }

  def average_rating
    total_rating = rating_animals.to_f + rating_earth.to_f + rating_materials.to_f + rating_people.to_f
    (total_rating / 4).round
  end

  def self.eco
    all.select do |brand|
      brand.average_rating >= 3 && brand.approved == true
    end
  end

  def eco?
    average_rating >= 3
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :naughty ]

  def ecofriendly
    @brand = Brand.find(params[:id])
    # TODO brand photos - cloudinary
    @brands = Brand.eco
    @suggested_brands = @brands.select do |brand|
      brand.price_category == @brand.price_category && brand.style == @brand.style unless brand == @brand
    end
  end

  def naughty
  #also create a view - for its own page
    @brand = Brand.find(params[:id])
    @newsarticles = NewsArticle.all
    @news = @newsarticles.order(created_at: :desc)
    @topnews = @news.first(3)
    @allbrands = Brand.eco
    @suggested_brands = @allbrands.select do |newbrand|
      newbrand.price_category == @brand.price_category && newbrand.style == @brand.style
    end
    # price and style overlap
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(brand_params)
    # byebug
    if @brand.save
      if current_user.brands_referred.nil?
        current_user.brands_referred = 1
      else
        current_user.brands_referred += 1
      end
      current_user.save
    else
      flash[:alert] = 'Brand already exists.'
      redirect_to explore_brands_path
    end
    # respond_to do |format|
    #   format.js
    # end
  end

  def explore
    @newsarticles = NewsArticle.all
    @brands = Brand.eco
    @brand = Brand.new

    @brands = Brand.where("name ILIKE ?", "%#{params[:query]}%").eco if params[:query].present?

    if params[:query].present? || params[:query] == ''
      respond_to do |format|
        format.html
        format.text { render partial: 'brands/brands_list', locals: { brands: @brands }, formats: [:html] }
      end
    end

    @newsarticles = NewsArticle.where("title ILIKE ?", "%#{params[:news_query]}%") if params[:news_query].present?

    if params[:news_query].present? || params[:news_query] == ''
      respond_to do |format|
        format.html
        format.text { render partial: 'brands/news_list', locals: { newsarticles: @newsarticles }, formats: [:html] }
      end
    end
  end

  def local

    if params[:address].present?
      @address = params[:address]
    else
      @address = current_user.address
    end
    @local_brands = Brand.near(@address, 2)
    @eco_local_brands = @local_brands.select do |brand|
      brand.eco? && brand.geocoded?
    end

    @markers = @eco_local_brands.map do |brand|
      {
        lat: brand.latitude,
        lng: brand.longitude,
        info_window: render_to_string(partial: "info_window", locals: { brand: brand }),
      }
    end
  end

  def saved
    @saved_brands = current_user.saved_brands
  end

  def save
    @saved_brand = SavedBrand.new(brand_id: params[:id])
    if current_user
      @saved_brand.user = current_user
      if @saved_brand.save!
        redirect_to saved_brands_path
        flash[:notice] = 'Brand saved successfully'
      else
        flash[:alert] = 'Brand was not saved.'
      end
    else
      redirect_to new_user_session_path
    end
  end

  def share
    if current_user == nil
    else
      if current_user.brands_shared.nil?
        current_user.brands_shared = 1
      else
        current_user.brands_shared += 1
      end
      current_user.save!
    end
    flash[:notice] = 'Thank you for sharing!'
    redirect_to ecofriendly_brand_path(params[:id])
  end

  private

  def brand_params
    params.require(:brand).permit(:name, :website_url, :insta_url, :price_category, :rating_earth, :rating_people, :rating_animals,:rating_materials, :about, :why_we_love_them, :address, :splash_image, :style)
  end

  def saved_brand_params
    params.require(:brand).permit(:brand_id)
  end
end

app/views/brands/_brands_list.html.erb
<div class="d-flex flex-wrap justify-content-between" data-search-brand-cards-target="cards">
  <% brands.each do |brand| %>
    <div class="mt-1" style= "width: 24.75%">
      <%= render 'brands/card_improved', brand: brand %>
    </div>
  <% end %>
</div>

app/views/brands/_card_improved.html.erb
<div class="original-size" data-controller="brand-card" data-action="mouseenter->brand-card#changeCard mouseleave->brand-card#changeCardBack" data-brand-card-target="shadow">
  <%# Non-expanded %>
  <div>
    <div data-brand-card-target="card" class="centered-text" style="background-image: linear-gradient( rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5) ), url('<%= brand.splash_image %>')">
      <p><strong><%= brand.name %></strong></p>
    </div>
  </div>

  <%# Expanded %>
  <div data-brand-card-target="info" class="hidden">
    <div class="card-slideshow">
      <%= render 'brands/slideshow', brand: brand %>
    </div>

    <div class="card-info">
      <div class="p-3">
        <div class="d-flex">
          <%# brand name %>
          <div class="mr-auto">
            <p style="color: black;"><strong><%= brand.name %></strong></p>
          </div>

          <%# logic for save btn %>
          <div style="z-index: 1">
            <% if current_user %>
              <% if current_user.brands.include?(brand)%>
                <i class="fas fa-heart saved-btn"></i>
              <% else %>
                <%= link_to save_path(brand.id), method: :post, class: "save-btn" do %>
                  <i class="far fa-heart" aria-hidden="true"></i>
                <% end %>
              <% end %>
            <% else %>
              <%= link_to save_path(brand.id), method: :post, class: "save-btn" do %>
                <i class="far fa-heart" aria-hidden="true"></i>
              <% end %>
            <% end %>
          </div>
        </div>

        <%# ratings %>
        <div class="d-flex">
          <div class="d-flex">
            <% brand.average_rating.times do %>
              <i class="fas fa-globe-americas mx-1 mt-2">  </i>
            <% end %>
            <% (5 - brand.average_rating).times do %>
              <i style="color: gainsboro" class="fas fa-globe-americas mx-1 mt-2">  </i>
            <% end %>
          </div>
          <div class="ml-auto">
            <% brand.price_category.times do %>
              <i class="fas fa-pound-sign"></i>
            <% end %>
            <% (3 - brand.price_category).times do %>
              <i style="color: gainsboro" class="fas fa-pound-sign">  </i>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= link_to '', ecofriendly_brand_path(brand), class: "card-link" %>
</div>

app/views/brands/_ecofriendly_accordian.html.erb
<div class="accordion" id="accordionExample">

  <%# First collapsable - Impact - default visible %>
  <div class="card">
    <div class="card-header" id="headingOne">
      <h2 class="mb-0">
        <button class="measure-button btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
          Impact <i style="color: gray" id="expand" class="fas fa-plus"></i>
        </button>
      </h2>
    </div>
    <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
      <div class="measure-display">
        <div class="measure-descriptions" data-controller="tooltip">
          <p data-toggle="tooltip" data-placement="left" title="CO2 footprint"><%= "Earth" %></p>
          <p data-toggle="tooltip" data-placement="left" title="Working conditions"><%= "People" %></p>
          <p data-toggle="tooltip" data-placement="left" title="Animal welfare"><%= "Animals" %></p>
          <p data-toggle="tooltip" data-placement="left" title="Eco-friendly materials"><%= "Materials" %></p>
        </div>

        <div class="measures">
          <div class="earth-rating">
            <p>
              <% @brand.rating_earth.times do %>
                <i class="fas fa-globe-americas mx-1">  </i>
              <% end %>
              <% (5 - @brand.rating_earth).times do %>
                <i style="color: #8395a1" class="fas fa-globe-americas mx-1">  </i>
              <% end %>
            </p>
          </div>
          <div class="people-rating">
            <p>
              <% @brand.rating_people.times do %>
                <i class="fas fa-user mx-1">  </i>
              <% end %>
              <% (5 - @brand.rating_people).times do %>
                <i style="color: #DBCF96;" class="fas fa-user mx-1">  </i>
              <% end %>
            </p>
          </div>
          <div class="animals-rating">
            <p>
              <% @brand.rating_animals.times do %>
                <i class="fas fa-paw mx-1">  </i>
              <% end %>
              <% (5 - @brand.rating_animals).times do %>
                <i style="color: #bd8379" class="fas fa-paw mx-1">  </i>
              <% end %>
            </p>
          </div>
          <div class="materials-rating">
            <p>
              <% @brand.rating_materials.times do %>
                <i class="fas fa-recycle mx-1">  </i>
              <% end %>
              <% (5 - @brand.rating_materials).times do %>
                <i style="color: #ACBEA3" class="fas fa-recycle mx-1">  </i>
              <% end %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%# Collapsable 2 - Why we love them - default hidden %>
  <div class="card">
    <div class="card-header" id="headingTwo">
      <h2 class="mb-0">
        <button class="measure-button btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Why we love them <i style="color: gray" id="expand" class="fas fa-plus"></i>
        </button>
      </h2>
    </div>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
      <div class="card-body1">
        <p><%= @brand.why_we_love_them %></p>
      </div>
    </div>
  </div>

  <%# Collapsable 3 - About - default hidden %>
  <div class="card">
    <div class="card-header" id="headingThree">
      <h2 class="mb-0">
        <button class="measure-button btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          About <i style="color: gray" id="expand" class="fas fa-plus"></i>
        </button>
      </h2>
    </div>
    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
      <div class="card-body1">
        <p><%= @brand.about %></p>
      </div>
    </div>
  </div>

  <%# Collapsable 4 - Location - TODO MAP - default hidden %>
  <div class="card">
    <div class="card-header" id="headingFour">
      <h2 class="mb-0">
        <button class="measure-button btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
          Location <i style="color: gray" id="expand" class="fas fa-plus"></i>
        </button>
      </h2>
    </div>
    <div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordionExample">
      <div class="card-body1">
        <p><%= @brand.address %></p>
      </div>
    </div>
  </div>
</div>

app/views/brands/_info_window.html.erb
<div style="width: 300px; height: auto;">

  <%= render 'card_improved', brand: brand %>

</div>

app/views/brands/_naughty_accordian.html.erb
<div class="accordion" id="accordionExample">

  <%# First collapsable - Impact - default visible %>
  <div class="card">
    <div class="card-header" id="headingOne">
      <h2 class="mb-0">
        <button class="measure-button btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
          Impact <i style="color: gray" id="expand" class="fas fa-plus"></i>
        </button>
      </h2>
    </div>
    <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
      <div class="measure-display">
        <div class="measure-descriptions" data-controller="tooltip">
          <p data-toggle="tooltip" data-placement="left" title="CO2 footprint"><%= "Earth" %></p>
          <p data-toggle="tooltip" data-placement="left" title="Working conditions"><%= "People" %></p>
          <p data-toggle="tooltip" data-placement="left" title="Animal welfare"><%= "Animals" %></p>
          <p data-toggle="tooltip" data-placement="left" title="Eco-friendly materials"><%= "Materials" %></p>
        </div>

        <div class="measures">
          <div class="earth-rating">
            <p>
              <% @brand.rating_earth.times do %>
                <i class="fas fa-globe-americas mx-1">  </i>
              <% end %>
              <% (5 - @brand.rating_earth).times do %>
                <i style="color: #8395a1" class="fas fa-globe-americas mx-1">  </i>
              <% end %>
            </p>
          </div>
          <div class="people-rating">
            <p>
              <% @brand.rating_people.times do %>
                <i class="fas fa-user mx-1">  </i>
              <% end %>
              <% (5 - @brand.rating_people).times do %>
                <i style="color: #DBCF96;#bd8379;" class="fas fa-user mx-1">  </i>
              <% end %>
            </p>
          </div>
          <div class="animals-rating">
            <p>
              <% @brand.rating_animals.times do %>
                <i class="fas fa-paw mx-1">  </i>
              <% end %>
              <% (5 - @brand.rating_animals).times do %>
                <i style="color: #bd8379" class="fas fa-paw mx-1">  </i>
              <% end %>
            </p>
          </div>
          <div class="materials-rating">
            <p>
              <% @brand.rating_materials.times do %>
                <i class="fas fa-recycle mx-1">  </i>
              <% end %>
              <% (5 - @brand.rating_materials).times do %>
                <i style="color: #ACBEA3" class="fas fa-recycle mx-1">  </i>
              <% end %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%# Collapsable 2 - Why we love them - default hidden %>
  <div class="card">
    <div class="card-header" id="headingTwo">
      <h2 class="mb-0">
        <button class="measure-button btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          About <i style="color: gray" id="expand" class="fas fa-plus"></i>
        </button>
      </h2>
    </div>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
      <div class="card-body1">
        <p> <%= @brand.about %></p>
      </div>
    </div>
  </div>

</div>

app/views/brands/_news_card.html.erb
<%# <link rel="stylesheet" href=<%news.url%>
<%= link_to news.url, target: "_blank" do%>
  <div class="info-card news-card">
    <%= image_tag news.image, class: "card-img-top"  %>
    <div class = "p-3">
      <div class = "d-flex">
        <div class = "mr-auto max">
          <p class = "margin"><strong><%= truncate(news.title, length: 24, separator: ' ') %></strong></p>
          <p class = "news-font"><%= truncate(news.blurb, length: 80, separator: ' ')%></p>
          <div class="news-date">
            <p class= "date news-font"><%= news.date  %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
<%end%>

app/views/brands/_news_list.html.erb
<div data-search-news-target="articles" class = "news-container">
  <% newsarticles.each do |news| %>
    <div style="width: 32%; margin-top: 1.9%;">
      <%= render 'brands/news_card', news: news %>
    </div>
  <% end %>
</div>

app/views/brands/_news_slideshow.html.erb
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel('cycle')">
  <div class="carousel-inner">
    <div class="carousel-item active background-img" style="background-image: linear-gradient( rgba(0, 0, 0, 0.1), rgba(0, 0, 0, 0.2) ), url('<%= image_path 'naughty1.png' %>')">
    </div>
      <div class="carousel-item background-img" style="background-image: linear-gradient( rgba(0, 0, 0, 0.1), rgba(0, 0, 0, 0.2) ), url('<%= image_path 'naughty2.png' %>')">
      </div>
      <div class="carousel-item background-img" style="background-image: linear-gradient( rgba(0, 0, 0, 0.1), rgba(0, 0, 0, 0.2) ), url('<%= image_path 'naughty3.png' %>')">
      </div>
  </div>
 <button class="carousel-control-prev" type="button" data-target="#carouselExampleControls" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-target="#carouselExampleControls" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </button>
</div>

app/views/brands/_search.html.erb
<%= form_tag(
    explore_brands_path, method: 'get',
    class: "form-inline col-12",
    data: {search_brand_cards_target: "form"},
    autocomplete: "off"
  ) do %>
  <div class="search-bar" id="outlined-search" data-search-brand-cards-target="search">
    <i class="fas fa-search d-inline"></i>
    <%= text_field_tag :query,
      params[:query],
      class: "d-inline search-input",
      placeholder: "Search brand",
      data: {
        action: "keyup->search-brand-cards#updateBrandsIndex",
        search_brand_cards_target: "input"
      }
    %>
  </div>
<% end %>

app/views/brands/_search_ecobrand.html.erb
<%= form_tag(
    explore_brands_path, method: 'get',
    class: "form-inline col-12",
    data: {search_brand_cards_target: "form"},
    autocomplete: "off"
  ) do %>
  <div class="search-bar" id="outlined-search" data-search-brand-cards-target="search">
    <i class="fas fa-search d-inline"></i>
    <%= text_field_tag :query,
      params[:query],
      class: "d-inline search-input",
      placeholder: "Search eco-brand",
      data: {
        action: "keyup->search-brand-cards#updateBrandsIndex",
        search_brand_cards_target: "input"
      }
    %>
  </div>
<% end %>

app/views/brands/_search_news.html.erb
<%= form_tag(
    explore_brands_path, method: 'get',
    class: "form-inline col-12",
    data: {search_news_target: "form"},
    autocomplete: "off"
  ) do %>
  <div class="search-bar" id="outlined-search" data-search-news-target="search">
    <i class="fas fa-search d-inline"></i>
    <%= text_field_tag :news_query,
      params[:news_query],
      class: "d-inline search-input",
      placeholder: "Search news",
      data: {
        action: "keyup->search-news#updateNews",
        search_news_target: "input"
      }
    %>
  </div>
<% end %>

app/views/brands/create.js.erb
$('#suggestBrandModal').modal('hide')

app/views/brands/local.html.erb
<%= render 'shared/navbar' %>

<div class="mt-5 mb-4">
  <div class="page-layout-with-back-btn">
    <div class="back-btn-container">
      <%= link_to 'javascript:history.go(-1);' do %>
        <button class="icon-btn">
          <i class="fas fa-chevron-left"></i>
        </button>
      <% end %>
    </div>

    <div class="container">
      <div>
        <h1>Eco-brands near you</h1>
      </div>
      <div class="brands-list d-flex">
        <% @eco_local_brands.each do |brand| %>
        <div class="local-card">
          <%= link_to "#{brand.name}", ecofriendly_brand_path(brand), id: "local-card-text"  %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="map-container">
  <div class="map" data-controller="local-modal">
    <div class="map-body" style="width: 100%; height: 600px;"
      data-controller="mapbox"
      data-mapbox-markers-value="<%= @markers.to_json %>"
      data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
      data-action="click->mapbox#openModal">
    </div>
    <%# -----------SEARCH---------- %>
    <div class="map-search">
      <%= form_tag(
        local_brands_path, method: 'get',
        class: "form-inline",
        ) do %>
        <div class="map-search-bar">
          <i class="fas fa-search d-inline"></i>
          <%= text_field_tag :address,
            params[:address],
            class: "d-inline search-input",
            placeholder: "#{@address}"
          %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/brands/naughty.html.erb
<%= render 'shared/navbar' %>

<div class="mt-5">
  <div class="page-layout-with-back-btn">
    <div class="back-btn-container">
      <%= link_to 'javascript:history.go(-1);' do %>
        <button class="icon-btn">
          <i class="fas fa-chevron-left"></i>
        </button>
      <% end %>
    </div>

    <div class="container">
      <div class="row mb-5">
        <div class = "slideshow col-6 h-75">
          <%= render 'news_slideshow', locals: { topnews: @topnews } %>
        </div>

        <div class="col-5">
          <div class="brand-show-header">
            <div class="mb-2">
              <h1 class="d-inline align-middle"><%= @brand.name %></h1>
              <span class="pill d-inline align-middle"><%= @brand.style.capitalize %> style</span>
              <span class="pill d-inline align-middle color-bad"><i class="far fa-thumbs-down"></i></span>

            </div>

            <div class="d-flex mb-3">
              <div class="d-flex">
                <% @brand.average_rating.times do %>
                  <i class="fas fa-globe-americas mx-1 mt-2">  </i>
                <% end %>
                <% (5 - @brand.average_rating).times do %>
                  <i style="color: grey" class="fas fa-globe-americas mx-1 mt-2">  </i>
                <% end %>
              </div>
            </div>
          </div>

          <div class="mt-2">
            <%= render 'naughty_accordian', locals: { brand: @brand } %>
          </div>
        </div>
      </div>

      <div class="similar-brands mt-3">
        <h3>Similar eco-brands brands for you</h3>
        <div class="scroll p-0">
          <div class="row justify-content-start">
            <% @suggested_brands.first(10).each do |brand| %>
              <div style="width: 300px;">
              <%= render 'brands/card_improved', brand: brand %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>